services:
  transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcriber
    expose:
      - 65535:65535
    networks:
      - careerspeak
    volumes:
      - ../voice:/voice:ro

networks:
  careerspeak:
    external: true


